name: Bump module.json version on push

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'ci: bump version') && github.actor != 'github-actions[bot]'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Bump module.json version
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: node .github/scripts/bump-module-version.js
